# Lec09 Numpy III：变型和广播 Reshape and Broadcasting 

In [3]:
import numpy as np
np.random.seed(0)

## 9.1 变形 reshape

### 9.1.1 变形 reshape

在前面我们已经了解了reshape功能。几天再介绍一种简练语法。

In [8]:
x = np.array([1, 2, 3])

生成行向量

In [9]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [10]:
x[np.newaxis, :]

array([[1, 2, 3]])

生成列向量

In [11]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [12]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### 9.1.2 拼接 Concatenation

``np.concatenate``

In [18]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [19]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [21]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid]) #默认按照编号0的轴，也就是Y轴

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
np.concatenate([grid, grid], axis=1) #按照编号1的轴，也就是X轴

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

沿着固定方向处理数组，``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack)更方便。

In [23]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])


np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [24]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

``np.dstack``将按照第三个维度拼接

### 9.1.3 拆分 Splitting

输入一个拆分点的列表，表明分裂的位置。

In [25]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

 ``np.dsplit``可以实现按照第三个维度拆分。

### 9.1.4 转置 Transpose

In [51]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [55]:
arr_t = np.transpose(arr)
arr_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

``np.transpose``实际上是把两个轴的编码互换位置

In [59]:
print(np.shape(arr))
print(np.shape(arr_t))

(3, 5)
(5, 3)


对于多维数组，则要主动声明轴的变换。

In [60]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.transpose() # 由（2,2,4）变成（4,2,2），原来的第（i,j,k）元素变成第（k,j,i）

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [62]:
arr.transpose((1, 0, 2)) #对调前两个轴，由(2, 2, 4)变成(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [63]:
arr.transpose((2, 1, 0)) #由(2, 2, 4)变成(4, 2, 2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

轴交换

In [66]:
arr.swapaxes(1, 2) #仅仅交换两个轴，本例交换1和2两个轴

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [68]:
arr.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 9.2 广播 Broadcasting

### 9.2.1 认识广播

对于大小相同的数组，二元运算符会逐个元素相加

In [4]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

广播可以将二元运算符运用于不同大小的数组。

In [5]:
a + 5

array([5, 6, 7])

广播可以理解为将数值``5``扩展到数组 ``[5, 5, 5]``

下面的例子是一个高维数组的广播：

In [6]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

下面的例子涉及两个数组的同时广播：

In [26]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [27]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![广播](figures/9-1-broadcasting.png)

### 9.2.2 广播的规则 Rules of Broadcasting

- Rule 1: 如果两个数组的维度不同，那么小维度的数组的形状将会在最左边补1。
- Rule 2: 如果两个数组在任一维度上都不匹配，那么数组的形状会沿着维度为1的维度扩展，以匹配另一个数组的形状。
- Rule 3: 如果两个数组在任一维度上都不匹配，且没有任一个维度为1，则会引发异常。

**例1：二维数组和一维数组相加**

In [29]:
M = np.ones((2, 3))
a = np.arange(3)

两个数组的形状为：

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

根据rule 1 ，数组``a``的维度较少，所以在左边补1:

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

根据rule 2, 第一个维度不匹配，因此扩展这个维度以匹配:

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

现在形状匹配了，最终的形状为 ``(2, 3)``:

In [30]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

**例2：两个数组都需要广播**

In [32]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

首先写出两个数组的shape:

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

根据Rule 1， 我们在 ``b`` 左边补个1:

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

根据rule 2，我们更新连个数组的维度以相互匹配:

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

In [33]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

**例3：无法广播**

In [34]:
M = np.ones((3, 2))
a = np.arange(3)

首先写出两个数组的shape：

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

根据rule 1，我们给``a``左侧补个1:

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

根据rule 2，沿着维度为1的维度扩展，即扩展``a``以匹配``M``:

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

根据rule 3，最后的结果还是不匹配，所以会报错。

In [35]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

那么，你可能希望``a.shape = (3,)``右边补1，以使得两者匹配。但这不被广播的原则允许，那么应该怎么？

In [ ]:
a[:, np.newaxis].shape

In [ ]:
M + a[:, np.newaxis]

另外，例子中仅仅使用了``+``运算符，实际上所有的二元``ufunc``都可以广播

In [36]:
np.logaddexp(M, a[:, np.newaxis])

array([[1.31326169, 1.31326169],
       [1.69314718, 1.69314718],
       [2.31326169, 2.31326169]])

### 9.2.3 广播的应用 Broadcasting in Practice

归一化 Centering

In [38]:
X = np.random.random((10, 3))

In [39]:
Xmean = X.mean(0) #沿着编号0的轴，也就是Y轴
Xmean

array([0.52101579, 0.62614181, 0.59620338])

令``X``的每一列减去均值，实现归一化。这就是一个广播操作。

In [ ]:
X_centered = X - Xmean

我们来看看归一化后的结果是不是接近0

In [ ]:
X_centered.mean(0)

## 9.3 排序 Sorting

### 9.3.1 排序 Sorting

Numpy的``np.sort``是一个高速的排序算法。

如果想在补修改原数组的基础上，生成一个排好序的数组，就使用``np.sort``

In [40]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

如果想用排好序的数组取代原数组，就使用``sort`` method

In [41]:
x.sort()
print(x)

[1 2 3 4 5]


``argsort``会返回排好序的数组的索引值。

In [42]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


通过花式索引：

In [43]:
x[i]

array([1, 2, 3, 4, 5])

### 9.3.2 沿着行或列排序 Sorting along rows or columns

In [44]:
X =  np.random.randint(0, 10, (4, 6))
print(X)

[[3 2 7 2 0 0]
 [4 5 5 6 8 4]
 [1 4 9 8 1 1]
 [7 9 9 3 6 7]]


In [46]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [47]:
np.sort(X, axis=0) #沿着编号0的轴，也就是Y轴

array([[1, 2, 5, 2, 0, 0],
       [3, 4, 7, 3, 1, 1],
       [4, 5, 9, 6, 6, 4],
       [7, 9, 9, 8, 8, 7]])

In [48]:
np.sort(X, axis=1) #沿着编号1的轴，也就是X轴

array([[0, 0, 2, 2, 3, 7],
       [4, 4, 5, 5, 6, 8],
       [1, 1, 1, 4, 8, 9],
       [3, 6, 7, 7, 9, 9]])

### 9.3.3 部分排序 Partial Sorts

有时候我们不想对整个数组排序，仅仅希望找到第K小的值。

In [49]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

结果中前三个，是``x``中最小的三个数，后面的原始数组剩下的值。前后的排序都是任意的。

In [50]:
np.partition(X, 2, axis=1)

array([[0, 0, 2, 7, 3, 2],
       [4, 4, 5, 6, 8, 5],
       [1, 1, 1, 8, 4, 9],
       [3, 6, 7, 9, 9, 7]])

``np.argpartition`` 则可以得到相应的索引值。