# Lec07 Numpy I：认识Arrays

In [2]:
import numpy as np

In [ ]:
np.__version__

## 7.1 数组 array

### 7.1.1 创建数组 Creating ndarrays

最简单的办法，就是利用array函数，将其他序列型对象，转化成为NumPy的array数组。

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

它的数据类型为

In [ ]:
type(arr1)

二维数组是同样可以用嵌套list生成

In [3]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(arr2)

你可以调用数组的属性，查看数组的形状、维度等。

In [ ]:
arr2.shape

In [ ]:
arr2.size

In [ ]:
arr2.ndim

也可以用相应的函数

In [4]:
np.shape(arr2)

(2, 4)

In [5]:
np.size(arr2)

8

In [7]:
np.ndim(arr2)

2

同理，你还可以用嵌套列表创建更高维度的数据

In [20]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 7.1.2 数组变形 reshape

In [21]:
grid = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

上面的三维数组同样可以这样生成。

In [22]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape((2, 2, 2))
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [50]:
np.reshape(np.array([1, 2, 3, 4, 5, 6, 7, 8]), (2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 7.1.3 数组的数据类型 Data Types for ndarrays

| 数据类型 | 类型代码 | 说明 |
| ------ | ------- | ------- |
| int8、uint8   | i1、u1| 有符号和无符号的8位（1字节）整形| 
| int16、uint16 | i2、u2 | 有符号和无符号的16位（2字节）整形| 
| int32、uint32 | i3、u3 | 有符号和无符号的32位（4字节）整形| 
| int64、uint64 | i4、u4 | 有符号和无符号的64位（8字节）整形| 
| float16  | f2 | 半精度浮点数 | 
| float32  | f4或f | 单精度浮点数 |
| float64  | f8或d | 双精度浮点数 |
| float128 | f16或g | 扩展精度浮点数 |
| complex64 | c8 | 32位浮点数表示的复数 | 
| complex128 | c16 | 64位浮点数表示的复数 | 
| complex256 | c32 | 128位浮点数表示的复数 | 
| bool | ? | 储存 True 和 False 的布尔型 | 

数据类型，可以用numpy数据类型来设定。

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

In [9]:
arr2.dtype

dtype('int32')

也可以通过文字的数据类型来设定。

In [ ]:
arr3 = np.array([1, 2, 3], dtype='float64')
arr4 = np.array([1, 2, 3], dtype='u4')
arr3.dtype

In [ ]:
arr4.dtype

利用`astype`来设定数据类型

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings)
numeric_strings.astype(float)

In [ ]:
np.string_?

### 7.1.3 特殊数组 Special Arrays

| 函数    | 说明            |
| ------- | ------|
| array   | 将数据转换成数组 | 
| asrray   | 将数据转换成数组，如果本身就是数组就不转换了 | 
| arange   | 类似range，但是返回的是数组，不是列表 | 
| linspace   | (a, b, c)，将等分区间(a,b)等分成c-1份 |
| logspace   | (a, b, c)，生成等比数列，以10为底的a次幂到b次幂，分成c-1份 |
| ones、ones_like   | 全是1的数组，ones_like参照其他数组，创建全是1的数组 | 
| zeros、zeros_like   | 全是0的数组，zeros_like参照其他数组，创建全是0的数组 | 
| empty、empty_like   | 不做预设的数组，empty_like参照其他数组，创建无预设数组 | 
| eye、identity   | 单位矩阵 | 
| diag   | 对角线矩阵 | 
| full   | ((m, n), a)，用a把m*n的矩阵填满 | 
| meshgrid   | 用一维坐标向量，生成坐标矩阵 | 

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((3, 6))

In [ ]:
np.empty((2, 3, 2))
#np.empty会返回没有初始化的垃圾数值。
# (3,2)代表3行2列的矩阵，最前面的2代表有2个这样的矩阵 

In [ ]:
np.ones((5,5))

In [ ]:
np.eye(5)

In [35]:
np.diag(np.arange(0,20,5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

创造包含十个元素的数组，每个元素都是5.4

In [29]:
x1 = np.full(10, 5.4)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [24]:
5.4 * np.ones(10)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

也可以通过``fill`` method来实现这个效果

In [33]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [ ]:
np.arange(15)
#np.arange函数，是python内置的range函数的Numpy版本。

In [36]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
np.logspace(0, 2, 5) #从10**0=1 到 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

所有的这些函数，都加入其他参数，比如``dtype``

In [39]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
x = np.array([0, 1, 2])
y = np.array([0, 3, 6])
X, Y = np.meshgrid(x,y)

横轴三个坐标，纵轴三个坐标，一共生成9个坐标点。第一个坐标点为(0,0)。

In [44]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [45]:
Y

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [47]:
Z= (X+Y)**2
Z

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

## 练习

![练习1](figures/7-3.png)

![练习2](figures/7-4.png)

![练习3](figures/7-5.png)

![练习3](figures/7-7.png)

## 7.2 索引与切片 Indexing and Slicing

### 7.2.1 一维数组切片

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5]
arr[5:8]
arr[5:8] = 12
arr

+ 数组(Array)的索引是一个view，改了就真的改了，把源数据改了。
+ 列表(list)的索引是一个copy。
+ 如果仅仅是copy数组，就用arr[5:8].copy()

In [ ]:
arr_slice = arr[5:8]
arr_slice

In [ ]:
arr_slice[1] = 12345
arr

In [ ]:
arr_slice[:] = 64
arr

### 7.2.2 二维数组切片

![图片](figures/7-1.png)

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.shape

In [ ]:
arr2d[2] # 第一个维度，也就是行，中的第3行，也就是编号2的那一行

In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0, 2]

### 7.2.3 三维数组切片

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
arr3d

In [ ]:
arr3d.shape
# 2个 2乘3 的矩阵

In [ ]:
arr3d[0]

In [ ]:
arr3d[1, 0]

In [ ]:
x = arr3d[1]
x
x[0]

### 7.2.4 视图和副本 View and copy

In [4]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2d_sub = arr2d[:2, :2]
arr2d_sub

array([[1, 2],
       [4, 5]])

In [7]:
arr2d_sub[0, 0] = 99
arr2d_sub

array([[99,  2],
       [ 4,  5]])

In [8]:
arr2d

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

数组的切片返回的是数据的View，而不是Copy。所以修改切片的子数组，原数组也会改变。这是为了在处理大数据时便利和节约内存。

那么如何创造copy呢？

In [12]:
arr2d_sub_copy = arr2d[:2, :2].copy()
arr2d_sub_copy

array([[99,  2],
       [ 4,  5]])

In [13]:
arr2d_sub_copy[0, 0]= 42
arr2d_sub_copy

array([[42,  2],
       [ 4,  5]])

In [15]:
arr2d

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### 7.2.5 用切片做索引 Indexing with slices

In [ ]:
arr

In [ ]:
arr[1:6] 

In [ ]:
arr2d

In [ ]:
arr2d[:2] #没有逗号，所以是取第一个轴——横轴，从开头开始，取到编号为2的行之前。

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2] # 不是都有冒号就会被压缩维度

In [ ]:
arr2d[:2, 2] # 不是都有冒号就会被压缩维度

In [ ]:
arr2d[:, :1] # 都有冒号才能保持维度

In [ ]:
arr2d[:2, 1:] = 0
arr2d

![图片](figures/7-2.png)

## 练习

![练习4](figures/7-6.png)

### 7.2.6 布尔型索引 Boolean Indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

In [ ]:
data = np.random.randn(7, 4)
data

In [ ]:
names == 'Bob'

In [ ]:
data[[ True, False, False,  True, False, False, False]]

In [ ]:
data[names == 'Bob']

布尔型数组，可以作为数组的索引    
+ 布尔型数组的长度，必须和索引对象的长度相同
+ 当然，长度不匹配也不会报错，所以也要小心。

In [ ]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'
data[~(names == 'Bob')]

In [ ]:
names == 'Bob'

In [ ]:
~(names == 'Bob')

In [ ]:
# 把上面的代码写开 也可是这样
cond = names == 'Bob'
data[~cond]

In [ ]:
# 在布尔运算中，且是&，或是|
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data < 0

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### 7.2.7 花式索引 Fancy Indexing

+ 利用整数数组做索引
+ 花式索引或copy，而不是view

In [15]:
x = np.random.randint(100, size=10)
print(x)

[43 16 58  9 54 13 95 63  3 96]


如果你想或者其中三个不同的元素，你可以这样做：

In [17]:
[x[3], x[7], x[2]]

[9, 63, 58]

另一种方法是传递一个列表作为索引

In [16]:
ind = [3, 7, 4]
x[ind]

array([ 9, 63, 54])

利用花式索引，结果的形状和索引数组的形状一致

In [18]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[ 9, 63],
       [54, 13]])

对于多维数组也是同理

In [20]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

索引也可以组合

In [21]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [22]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

再来看下面的例子

In [9]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [10]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [11]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

对两个轴做花式索引

In [12]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [13]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # 仅仅抓出对应位置的元素

array([ 4, 23, 29, 10])