# Lec10 Numpy IV：数组的其他应用 

In [1]:
import numpy as np
np.random.seed(0)

## 10.1 伪随机数 Pseudorandom Number

| 常用的numpy.random函数 | 说明 |
| ------     | ------- |
| seed       | 确定随机数生成器的种子 | 
| permutation  | 返回一个序列排列的范围 | 
| shuffle      | 对一个序列进行随机排列 | 
| rand         | 产生均匀分布的样本值 | 
| randint      | 在给定范围内随机取整数 | 
| randn        | 产生标准正态分布的样本值 |
| binomial     | 产生二项分布的样本值 | 
| normal       | 产生正态分布的样本值 | 
| beta         | 产生beta分布的样本值 | 
| schisquare   | 产生卡方分布的样本值 | 
| gamma        | 产生Gamma分布的样本值 | 
| uniform      | 产生[0, 1]均匀分布的样本值 |

In [2]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [3]:
samples_2 = np.random.randn(4,4)
samples_2

array([[ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252]])

In [4]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

472 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
15.9 ms ± 384 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## 10.2 布尔数组与条件表达式

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [8]:
a < b

array([ True,  True, False, False])

可以对上述结果进行聚合

In [9]:
np.all(a < b)

False

In [10]:
np.any(a < b)

True

布尔运算一个很方便的应用就是省去写循环的麻烦：

In [12]:
x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [13]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [14]:
x * (x > 0)

array([0, 0, 0, 1, 2])

``np.where``函数是三元表示式“x if condition else y”的向量化版本。

In [15]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [16]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [17]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

再比如

In [ ]:
arr = np.random.randn(4, 4)
arr

In [ ]:
arr > 0

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

``np.select``则是根据条件和操作的列表作为条件

In [19]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [22]:
np.select([x < -1, x < 2, x >= 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

``np.choose``的第一个元素是一组索引，根据索引选择相应的运算

In [23]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

``np.nonzero``会返回非零的索引

In [24]:
abs(x) > 2

array([ True,  True, False, False, False, False, False,  True,  True])

In [25]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [26]:
x[np.nonzero(abs(x) > 2)] # Fancy索引

array([-4., -3.,  3.,  4.])

In [27]:
x[abs(x) > 2] # bool型索引

array([-4., -3.,  3.,  4.])

| 函数    | 说明            |
| ------- | ------|
| where  | 根据条件选择相应的操作 | 
| choose   | 根据索引，选择相应的操作 | 
| select   | 根据条件列表选择相应的操作 | 
| nonzero  | 返回非零元素的索引 | 
| logical_and  | 逐元素逻辑AND运算 | 
| logical_or  | 逐元素逻辑OR运算 | 
| logical_xor  | 逐元素逻辑XOR运算 | 
| logical_not  | 逐元素逻辑NOT运算 | 

## 10.4 矩阵和向量运算